### ISSUE TITLE
Problem with using multiple libraries

### ISSUE THREAD

**Issue by OttoKlaasen** [khoih-prog/ESP_WiFiManager#16]
Dear Sir,

when i use in my program following two libs:

#include <ESP_WiFiManager.h>              //https://github.com/khoih-prog/ESP_WiFiManager
#include "esp_http_server.h"

I am getting an error:

Building in release mode
Compiling .pio\build\esp32dev\src\main.cpp.o
Compiling .pio\build\esp32dev\libb6a\WebServer\Parsing.cpp.o
Compiling .pio\build\esp32dev\libb6a\WebServer\WebServer.cpp.o
Compiling .pio\build\esp32dev\liba7e\ESP_WiFiManager_ID6915\ESP_WiFiManager.cpp.o
In file included from C:/Users/ottok/.platformio/packages/framework-arduinoespressif32@src-537c58760dafe7fcc8a1d9bbcf00b6f6/tools/sdk/include/esp_http_server/esp_http_server.h:22:0,
                 from src\main.cpp:96:
C:/Users/ottok/.platformio/packages/framework-arduinoespressif32@src-537c58760dafe7fcc8a1d9bbcf00b6f6/tools/sdk/include/nghttp/http_parser.h:95:6: error: redeclaration of 'HTTP_DELETE'
   XX(0,  DELETE,      DELETE)   

Looks like in http_parser (called from: https://github.com/espressif/esp-idf/blob/master/components/esp_http_server/include/esp_http_server.h)  there is following declaration: 

/* Request Methods */
#define HTTP_METHOD_MAP(XX)         \
  XX(0,  DELETE,      DELETE)       \
  XX(1,  GET,         GET)          \
  XX(2,  HEAD,        HEAD)         \
  XX(3,  POST,        POST)         \
  XX(4,  PUT,         PUT)          \
  /* pathological */                \
  XX(5,  CONNECT,     CONNECT)      \
  XX(6,  OPTIONS,     OPTIONS)      \
  XX(7,  TRACE,       TRACE)        \
  /* WebDAV */                      \

and in HTTP_Method.h which is called from WebServer.h which is called from your code in case of ESP32 have a conflict:

#ifndef _HTTP_Method_H_
#define _HTTP_Method_H_

typedef enum {
  HTTP_GET     = 0b00000001,
  HTTP_POST    = 0b00000010,
  HTTP_DELETE  = 0b00000100,
  HTTP_PUT     = 0b00001000,
  HTTP_PATCH   = 0b00010000,
  HTTP_HEAD    = 0b00100000,
  HTTP_OPTIONS = 0b01000000,
  HTTP_ANY     = 0b01111111,
} HTTPMethod;

#endif /* _HTTP_Method_H_ */

Maybe you have an idea what to do in such a case ?

Kind Regards
Otto Klaasen

**Comment by khoih-prog** [comment]
This is the ESP32 issue, as ESP32's WebServer.h, on which this library depends on, have **some conflict with its own additional libraries** you're using. This has nothing to do with this library and not anything we here can do.

I just can suggest you do something like this is the code to see if it's OK and conflicting error solved. For example

```
typedef enum {
HTTP_GET = 0b00000001,
HTTP_POST = 0b00000010,

#if  !defined(HTTP_DELETE)
HTTP_DELETE = 0b00000100,
#endif

HTTP_PUT = 0b00001000,
HTTP_PATCH = 0b00010000,
HTTP_HEAD = 0b00100000,
HTTP_OPTIONS = 0b01000000,
HTTP_ANY = 0b01111111,
} HTTPMethod;

```
But be careful to use as I don't know this can break anything internally.
The preferable way is that you simplify the sketch or find some simple sketch to just do simple things, such as

```
#include <WebServer.h >
#include "esp_http_server.h"
```
to prove the compiler error, then post a new issue on [ESP32 Issues](https://github.com/espressif/esp-idf/issues)
