### ISSUE TITLE
Trying to save AWS cert and private key through custom parameters

### ISSUE THREAD

**Issue by miloshev** [khoih-prog/ESP_WiFiManager#19]
Hi,
I want to make esp32 thing connected to AWS IOT Core. For this i have to use cert and private key. Priv key is 1679 bytes, cert is 1224 bytes.
What will be the best way to enter them with custom parameter field and store them in the fs?

**Comment by khoih-prog** [comment]
Hi @miloshev 

Have a look at [ESP32_FSWebServer](https://github.com/khoih-prog/ESP_WiFiManager/tree/master/examples/ESP32_FSWebServer) to know how you can upload any file onto ESP32's SPIFFS.

Then you can either hardcode the file name or specify the file name in Custom Parameters.

The [ESP_WiFiManager](https://github.com/khoih-prog/ESP_WiFiManager) **doesn't dictate or has anything to do with where and how you store / retrieve / manage the Custom Parameters.**

I'm against using the Custom Parameters' fields to enter the long keys / certs.
