### ISSUE TITLE
ESP_WiFiManager-Impl.h comment trailing backslash breaks compilation

### ISSUE THREAD

**Issue by llarquere** [khoih-prog/ESP_WiFiManager#30]
System: Linux Mint 20 Ulyana
Arduino IDE: 1.8.13
Card: Heltec Wifi LoRa32 v2.1
Revision: recents
File: ESP_WiFiManager/src/ESP_WiFiManager-Impl.h
Method: ESP_WiFiManager::connectWifi
Line: 713

Hello KH,
the trailing (continuation) backslash at the end of this comment line
breaks the compilation, removing it and all goes well.

**Comment by khoih-prog** [comment]
Thanks. Will fix.
