### ISSUE TITLE
reconnectWifi misusage of connectWifi

### ISSUE THREAD

**Issue by llarquere** [khoih-prog/ESP_WiFiManager#31]
System: Linux Mint 20 Ulyana
Arduino IDE: 1.8.13
Card: Heltec Wifi LoRa32 v2.1
Revision: recents
File: ESP_WiFiManager/src/ESP_WiFiManager-Impl.h
Method: ESP_WiFiManager::reconnectWifi
Lines: 690,694

Hello KH,
the type of the method connectWifi is "int",
in the method reconnectWifi, "connectResult" have type "bool".
my suggestions :
- change "bool connectResult" to "int connectResult"
- change return code from "return connectResult" to "return connectResult == WL_CONNECTED"

**Comment by khoih-prog** [comment]
Good catch. Thanks.

Will change all to `int` for consistency

In [ESP_WiFiManager.h Line 456](https://github.com/khoih-prog/ESP_WiFiManager/blob/master/src/ESP_WiFiManager.h#L456)


```
    int           reconnectWifi(void);
```

In [ESP_WiFiManager-Impl.h Line 685-706](https://github.com/khoih-prog/ESP_WiFiManager/blob/master/src/ESP_WiFiManager-Impl.h#L685-L706)

```
int ESP_WiFiManager::reconnectWifi(void)
{
  int connectResult;
  
  // using user-provided  _ssid, _pass in place of system-stored ssid and pass
  if ( ( connectResult = connectWifi(_ssid, _pass) ) != WL_CONNECTED)
  {  
    LOGERROR1(F("Failed to connect to"), _ssid);
    
    if ( ( connectResult = connectWifi(_ssid1, _pass1) ) != WL_CONNECTED)
    {  
      LOGERROR1(F("Failed to connect to"), _ssid1);

    }
    else
      LOGERROR1(F("Connected to"), _ssid1);
  }
  else
      LOGERROR1(F("Connected to"), _ssid);
  
  return connectResult;
}
```
