### ISSUE TITLE
captive portal 

### ISSUE THREAD

**Issue by amar996** [khoih-prog/ESP_WiFiManager#36]
hi sir 

how can I add a captive portal for this library can you please help

**Comment by ILIJA-ILIEV** [comment]
Hello Sir,
is it possible to use WiFiManagerParameter how it is defined in tzapu/WiFiManager?

**Comment by khoih-prog** [comment]
@amar996 

I don't know how to answer your question. You have to clarify by posting your code or the details of your problem so that duplication is possible.

I'm closing the issue now. If you have more to add, just post the update.
