### ISSUE TITLE
How to use WiFiManagerParameter

### ISSUE THREAD

**Issue by khoih-prog** [khoih-prog/ESP_WiFiManager#37]
From @ILIJA-ILIEV 

> Hello Sir,
> is it possible to use WiFiManagerParameter how it is defined in tzapu/WiFiManager?

I'm moving your question to this new issue. Please don't post next time to non-relating one [captive portal: # 36](https://github.com/khoih-prog/ESP_WiFiManager/issues/36)

You can use WMParamenter the same way as in tzapu/WiFiManager. Just change the name from `WMParameter` to `ESP_WMParameter`.

For example:

```cpp
ESP_WMParameter custom_blynk_server("blynk_server", "blynk_server", blynk_server, BLYNK_SERVER_LEN + 1);
```

There are mane examples demonstrating how to use ESP_WMParameter, such as 

1. [**AutoConnectWithFSParameters**](https://github.com/khoih-prog/ESP_WiFiManager/blob/master/examples/AutoConnectWithFSParameters/AutoConnectWithFSParameters.ino)
2. [**ConfigOnDRD_FS_MQTT_Ptr**](https://github.com/khoih-prog/ESP_WiFiManager/blob/master/examples/ConfigOnDRD_FS_MQTT_Ptr/ConfigOnDRD_FS_MQTT_Ptr.ino)

and more.

**Comment by ILIJA-ILIEV** [comment]
Sorry, I didn't search properly maybe. Thanks for fast answer.
