### ISSUE TITLE
Consult MultiWiFi

### ISSUE THREAD

**Issue by joseperri** [khoih-prog/ESP_WiFiManager#42]
Hello my name is Jose, I am using the ESP_WiFiManager library in its latest version 1.20 and although everything works very well for my specific use, it would be better to be able to work with a single WIFI network, is there any configuration option that allows working exclusively with one NETWORK? At the moment what I am doing is using the library in version 1.011 in which MultiWiFi is not available
Since already very grateful for any suggestions

**Comment by khoih-prog** [comment]
HI Jose,

Good to know [**ESP_WiFiManager Library**](https://github.com/khoih-prog/ESP_WiFiManager) is so far working very well for you.

To use single WiFi, you can either 

1. use the previous v1.0.11 or 
2. just ignore the extra SSID1 input fields by leaving them blank

I'll consider, certainly not rush, to restore the ability to configure to use single WiFi in future releases although I still consider this is a step **backward**.
