### ISSUE TITLE
afraid.org changed their update URL

### ISSUE THREAD

**Issue by mariohaddad** [khoih-prog/ESP_WiFiManager#45]
instead of http://sync.afraid.org/u/TOKEN they are now using: 

https://freedns.afraid.org/dynamic/update.php?TOKEN

**Comment by khoih-prog** [comment]
I think you post at the **wrong** library.

Do you mean to post at [**DDNS_Generic Library**](https://github.com/khoih-prog/DDNS_Generic) ?

Anyway, I'm closing this now.
