### ISSUE TITLE
Hide or turn off SSID1 and PASSWORD1 field

### ISSUE THREAD

**Issue by VarconGitHub** [khoih-prog/ESP_WiFiManager#49]
Hello there
Is there any way to disable fields for SSID1 and PASSWORD1? I wont be using MultiWiFi feature
I succesfully disabled **USE_STATIC_IP_CONFIG_IN_CP** but i cant do the same for SSID1 and PASSWORD1

![Configuration](https://user-images.githubusercontent.com/58238927/103794531-1c23b600-5045-11eb-984e-54f6b92ca9da.png)

**Comment by khoih-prog** [comment]
I currently have no plan to provide that option for near future releases.

Please check the temporary solution in

[**Consult MultiWiFi #42**](https://github.com/khoih-prog/ESP_WiFiManager/issues/42)

If there are many more requests, I certainly will consider and spend some time to do or even create a SingleWiFi twin library.
