### ISSUE TITLE
ESP32 Wroom not working with library?

### ISSUE THREAD

**Issue by NazarDiadiun** [khoih-prog/ESP_WiFiManager#52]
Greetings!

Tried your library, works great with ESP32 Wroover-B. But when I try to upload the same sketch to the board from the ESP32 Wroom, everything stops working.
I manually turn on the configuration server - a network appears, I connect to it, configure the access point. In the serial port, I see the local address 255.255.255.0
Accordingly, there is no internet connection.

Again, everything works great on the first board with ESP32 Wroover-B!

What could be the reason for this behavior?

Thanks in advance!

**Comment by khoih-prog** [comment]
Did you follow the correct steps when uploading the program to ESP32-WROOM? Check [**HOW TO PROGRAM THE ESP32-WROOM-32**](https://www.lab4iot.com/2019/07/14/tutorial-on-how-to-program-the-esp32-wroom-32-or-esp32f/)

If you did everything correctly, there are too many factors which can create the issue: bad board, some board incompatibility, bad wiring, wrong IDE settings, etc

I'm afraid only you can figure it out. You can post issue on [**ESP32 Forum**](https://www.esp32.com/viewforum.php?f=19) to ask for help as I can't guess any further.

This issue has nothing to do with the library, so I'm closing it now.
