### ISSUE TITLE
Invalid Json generated

### ISSUE THREAD

**Issue by energise** [khoih-prog/ESP_WiFiManager#60]
### Describe the bug

Hi! I was looking to use the json interface but found that some of the json that ESP_WifiManager outputs is invalid.

Eg - it outputs on /scan:

{"Access_Points":[{'SSID':'UPC434892', 'Encryption':true, 'Quality':'98'}, {'SSID':'Horizon Wi-Free', 'Encryption':true, 'Quality':'66'}, {'SSID':'vodafone-602D', 'Encryption':true, 'Quality':'32'}]}

This is great except that single quotes aren't allowed in json - only double quotes

https://findanyanswer.com/does-json-allow-single-quotes

### Steps to Reproduce

  http://192.168.4.1/scan

### Expected behavior

  valid json returned

### Actual behavior

  invalid json returned

### Screenshots

![image](https://user-images.githubusercontent.com/1935701/117545092-3fbf3300-b01c-11eb-92b4-9c730350ce63.png)

![image](https://user-images.githubusercontent.com/1935701/117544854-397c8700-b01b-11eb-8f2d-b6dcadda9410.png)

### Information

Please ensure to specify the following:

ESP8266
Arduino 1.8.13

Thanks for such an amazing library

**Comment by khoih-prog** [comment]
Hi @energise 

Thanks for your bug report and your encouraging words. The new [**ESP_WiFiManager** release v1.7.1](https://github.com/khoih-prog/ESP_WiFiManager/releases/tag/v1.7.1) has just been published, with your Contribution noted in [**Contributions and Thanks**](https://github.com/khoih-prog/ESP_WiFiManager#contributions-and-thanks).

Looking forward to receiving more Contributions of yours.

Regards,

---

### Releases v1.7.1

1. Fix **Json bug** in /scan. Check [**Invalid Json generated** #60](https://github.com/khoih-prog/ESP_WiFiManager/issues/60)
2. Fix **timezoneName not displayed in Info page.**
