### ISSUE TITLE
Starting configuration portal takes very long

### ISSUE THREAD

**Issue by lols** [khoih-prog/ESP_WiFiManager#84]
22:04:08.756 -> Open Config Portal without Timeout: Double Reset Detected
22:04:08.756 -> Starting configuration portal @ 192.168.4.1:80, SSID = ESP_ , PWD = MyESP_
22:05:08.756 -> [WM] WiFi.waitForConnectResult Done

Hi, how i can reduce this wait time? I'm running ESP32_FSWebServer_DRD.ino

**Comment by khoih-prog** [comment]
Hi @lols 

1. Try 

```
#define USE_ESP_WIFIMANAGER_NTP     false
```

Check

https://github.com/khoih-prog/ESP_WiFiManager/blob/69ec6b3e686485f04364277c6172e4a29ea64dce/examples/ESP32_FSWebServer_DRD/ESP32_FSWebServer_DRD.ino#L213-L215

2. Turn on max debug level = 4 and see what is going on then

```
#define _WIFIMGR_LOGLEVEL_    3
```

https://github.com/khoih-prog/ESP_WiFiManager/blob/69ec6b3e686485f04364277c6172e4a29ea64dce/examples/ESP32_FSWebServer_DRD/ESP32_FSWebServer_DRD.ino#L48-L49

It's possible `WiFiScan` is taking so long time in your environment (too many SSIDs, ???)

3. Which ESP32 board and core  are you using ? 

4. It's weird that 

```
22:04:08.756 -> Starting configuration portal @ 192.168.4.1:80, SSID = ESP_ , PWD = MyESP_
```

Is there something wrong with your board ?

---

You have to include the full debug terminal output along with full info (core, board, environment, etc) next time or the non-actionable issue will be ignored and closed.

Good Luck,
