### ISSUE TITLE
Captive Portal Not opening Automatically on Windows/ Mac

### ISSUE THREAD

**Issue by kapyaar** [khoih-prog/ESP_WiFiManager#85]
### Describe the bug

Hello, 

I am facing an issue that the captive portal window does not open automatically on Windows 10, or Mac. It does open on an IPhone though. For windows and Mac, If I type in the default IP (192.168.4.1) in the browser, then I can access the config portal. Is this just me? Or has anything changed?

### Steps to Reproduce

Use the "ConfigOnStartup" Example provided in library, and connect to the access point (with password). I also tried disabling NTP, but no difference.

### Expected behavior

Expecting the captive portal window to open automatically. But it does not.

### Actual behavior

Captive Portal Window does not open automatically. Need to open a browser and go to 192.168.4.1 to get to config portal.

### Information

* Arduino IDE version (1.8.19)
* `ESP8266`  Core Version (v3.0.2)
* Contextual information (Trying to simply open captive portal window automatically)
* Simplest possible steps to reproduce
  * Operating system (Windows)

**Comment by khoih-prog** [comment]
Hi @kapyaar 

Can you try the [**ESPAsync_WiFiManager** library](https://github.com/khoih-prog/ESPAsync_WiFiManager), or any different **WiFiManager** library to see if Windows / Mac are doing OK with Captive Portal?

If not, I now have no idea why ? It's possibly

1. **Browser dependent**, such as `IPhone Safari` / Google Chome, etc. ???
2. **Safety measures** (again hacker, virus, etc.) in Windows / Mac to block the auto-modification of the HTTP(S) ???
3. Some **antivirus / extensions** in the browser to block the Captive Portal ???

You can try by using different Browsers, disabling antivirus, modifying settings, etc. to see if OK.

Please post your findings here to shed some light of what's wrong (library, Browser or Windows / Mac).

I'm sorry I don't have time to investigate this **special yet complex** issue and have to close it, and won't reopen until a library's bug is proven.

Good Luck,
