### ISSUE TITLE
Which SPIFFS.h?

### ISSUE THREAD

**Issue by kotakomputer** [khoih-prog/ESP_WiFiManager#9]
There are so many SPIFFS libraries, which one should we use  for your WifiManager?

**Comment by khoih-prog** [comment]
The ESP_WiFiManager actually doesn't care about which library and how you use to save the optional ESP_WMParameter.

You can use EEPROM, SPIFFS, etc. to save, and use ArduinoJson, direct binary write/read, etc. to help format / write / retrieve data.

The popular way is to use **_SPIFFS combined with ArduinoJson_**, as you can see in example [AutoConnectWithFSParameters](examples/AutoConnectWithFSParameters)

You don't need to do anything special to select which SPIFFS library to use, as it's already auto-selected by Arduino IDE when you specify either ESP8266 or ESP32 board.

To be more clearly, 

1. ESP8266 will automatically use ./hardware/esp8266com/esp8266/cores/esp8266/spiffs/spiffs.h, you have to use only
```
#include <FS.h>
```

2. ESP32 will automatically use ./hardware /espressif/esp32/libraries/SPIFFS/src/SPIFFS.h, but you have to use

```
#include <FS.h>
#include "SPIFFS.h"
```

Hereafter is the code snippet from the above-mentioned example

```
//Ported to ESP32
#ifdef ESP32
#include <FS.h>
#include "SPIFFS.h"
#include <esp_wifi.h>
#include <WiFi.h>
#include <WiFiClient.h>
...
#else
#include <FS.h>                   //this needs to be first, or it all crashes and burns...

#include <ESP8266WiFi.h>          //https://github.com/esp8266/Arduino
//needed for library
#include <DNSServer.h>
#include <ESP8266WebServer.h>
...
#endif
...
#include <ESP_WiFiManager.h>              //https://github.com/khoih-prog/ESP_WiFiManager

// Now support ArduinoJson 6.0.0+ ( tested with v6.14.1 )
#include <ArduinoJson.h>          //https://github.com/bblanchon/ArduinoJson
```
